In [1]:
from ucimlrepo import fetch_ucirepo
rice = fetch_ucirepo(id=545)
from logistic_regression import LogisticRegression
model = LogisticRegression(rice["data"]["original"])

In [2]:
model.clip_feature(0, 8459, 17663)
model.clip_feature(3, 67.7, 104)
model.clip_feature(4, 0.825, 0.935)
model.clip_feature(5, 8519, 17961)
model.scale_features()

In [3]:
model.split_data(0.8)

In [4]:
# model.GD(0.05, 30000)

In [13]:
model.GD(0.05, 1000, lambda_=0.1)

Epoch:  0
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  1
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  2
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  3
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  4
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  5
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  6
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  7
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  8
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  9
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  10
	Training accuracy:  0.5800524934383202
	Test accuracy:  0.5406824146981627
Epoch:  11
	Training accuracy:  0.5800524934383202
	T

In [77]:
model.GD(0.05, 100, lambda_=0.01, reset_weights=False)

Epoch:  0
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  1
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  2
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  3
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  4
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  5
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  6
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  7
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  8
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  9
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  10
	Training accuracy:  0.42913385826771655
	Test accuracy:  0.4645669291338583
Epoch:  11
	Training accuracy:  0.42913385

In [7]:
import numpy as np

In [8]:
a = np.array([-1.5, 2, 3, -4.78])

In [9]:
a

array([-1.5 ,  2.  ,  3.  , -4.78])

In [10]:
np.abs(a)

array([1.5 , 2.  , 3.  , 4.78])

In [11]:
a

array([-1.5 ,  2.  ,  3.  , -4.78])